### ISSUE TITLE
Using username and password in JSON with POST request for authentication

### ISSUE THREAD

**Issue by labros-zotos** [webhookdb/webhookdb#906]
Is there support to create an integration that receives data (poll & backfill) from APIs that use a JSON body as below and a POST request instead of get to authenticate on every request?
```
POST Body:
{
   username: "example",
   password: "pass"
}
```
I know it's not the best authentication method or practice as you make a POST requests for anything even to receive a list of products. But this is a thrid-party API that our company uses and I cannot make changes to it.

I looked through the integrations included in the repo but I can't find any similar examples. Or how to change the way webhookdb builds the request when polling an API in order to handle the method used.

Thank you.

**Comment by rgalanakis** [comment]
Hi @labros-zotos , that should not be a problem. The way the replicators/integrations call APIs is implemented by the replicator code because we definitely cannot make assumptions that all APIs follow good practices :)

Here is an example: https://github.com/webhookdb/webhookdb/blob/main/lib/webhookdb/replicator/transistor_episode_v1.rb#L161

The relevant code there is:

```rb
    response = Webhookdb::Http.get(
      url,
      headers: {"x-api-key" => self.service_integration.backfill_key},
      body: {pagination: {page: pagination_token, per: 500}},
      logger: self.logger,
      timeout: Webhookdb::Transistor.http_timeout,
    )
```

In your case, it'd be like:

```rb
    response = Webhookdb::Http.get(
      url,
      body: {username: self.backfill_key, password: self.backfill_secret},
      logger: self.logger,
      timeout: 30,
    )
```

And in case that's not enough: overriding `_fetch_backfill_page` is the simplest backfilling replicator- there are other replicators that need much more complex backfiling logic. For example, the Sponsy integrations have a 'customers' resource type, but there are no corresponding 'customer' API endpoints in the Sponsy API. So the backfiller actually looks in the database and pulls out customers, rather than make any HTTP requests at all: https://github.com/webhookdb/webhookdb/blob/43b81f062b04dd958d6310c50c0812d91e9cfa18/lib/webhookdb/replicator/sponsy_customer_v1.rb#L31

So you can create a custom `Backfiller` type (see `Webhookdb::Backfiller`) and then return it from `_backfillers`.

Let me know if that makes sense or not.

**Comment by labros-zotos** [comment]
Hi,
Thank you for your answer and help.
I just started working with webhookdb and although there is not a lot of documentation around it I really admire how well thought out and flexible it is.
It worked fine as you suggested with the following code:
```
response = Webhookdb::Http.post(
      url,
      headers: {"Content-Type" => "application/json"},
      body: {username: self.service_integration.backfill_key, password: self.service_integration.backfill_secret}.to_json,
      logger: self.logger,
      timeout: 30,
    )
```

**Comment by rgalanakis** [comment]
Thanks for the kind words!
